### ISSUE TITLE
How to configure this cliend for Azure Service Bus? 

### ISSUE THREAD

**Issue by Veerbhadra277** [rabbitmq/rabbitmq-amqp1.0#56]
I could easily configure with rabbitMQ, but i want to use Azure Service Bus which is also following AMQP protocol, I followed following document url, but couldn't help

[https://www.rabbitmq.com/erlang-client-user-guide.html#amqp-uris](https://www.rabbitmq.com/erlang-client-user-guide.html#amqp-uris)

Can anyone know how to achieve this?

Thanks,
Veer

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes two things:

1. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team)
2. We have a certain amount of information to work with

We get at least a dozen of questions through various venues every single day, often quite light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because of that questions, investigations, root cause analysis, discussions of potential features are all considered to be mailing list material by our team. Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing, or at least sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html)

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have enough details and evidence we'd be happy to file a new issue.

Thank you.

**Comment by michaelklishin** [comment]
This is an AMQP 1.0 server implementation. You are trying to use an [AMQP 0-9-1](https://www.rabbitmq.com/tutorials/amqp-concepts.html) Erlang client. Despite the names, AMQP 0-9-1 and AMQP 1.0 are very different protocols, not different versions of the same thing.

If you are looking for an Erlang AMQP 1.0 client, [our team has developed one](https://github.com/rabbitmq/rabbitmq-amqp1.0-client) and it is tested against Azure (with one configuration caveat that only Azure requires, by the way).
